
[Blocks]
	#Range: > 1
	totalFermentationTime = 6000
	#Range: 10 ~ 1000
	maxFluidLevel = 100
	#Range: 1 ~ 1000
	maxFluidPerJuice = 25
	#Range: 1 ~ 1000
	applePressMaxMashingProgress = 600
	#Range: 1 ~ 1000
	applePressMaxFermentingProgress = 800
	#Range: 0.0 ~ 1.0
	cherryGrowthChance = 0.4
	#Range: 0.0 ~ 1.0
	appleGrowthChance = 0.4
	#Range: 0.0 ~ 1.0
	grapeGrowthChance = 0.5

[Items]

	[Items.Wine]
		#Range: 1 ~ 10
		maxLevel = 5
		#Range: 1 ~ 100000
		startDuration = 1800
		#Range: 1 ~ 10000
		durationPerYear = 200
		#Range: 1 ~ 100
		daysPerYear = 24
		#Range: 1 ~ 100
		yearsPerEffectLevel = 6
		#Range: 1 ~ 100000
		maxDuration = 15000

	[Items.Banner]
		giveEffect = true
		showTooltip = true

	[Items.Basket]
		basketBlacklist = ["vinery:basket"]

	[Items.WanderingTrader]
		#Range: 0.0 ~ 1.0
		spawnChance = 0.5
		spawnWithMules = true
		#Range: > 1
		spawnDelay = 48000

	[Items.VillagerTrades]
		level1Trades = ["vinery:red_grape|5|4|5|false", "vinery:white_grape|5|4|5|false", "vinery:red_grape_seeds|2|1|1|true", "vinery:white_grape_seeds|2|1|1|true"]
		level2Trades = ["vinery:wine_bottle|1|2|7|true"]
		level3Trades = ["vinery:flower_box|3|1|10|true", "vinery:white_grape_bag|7|1|10|true", "vinery:red_grape_bag|7|1|10|true"]
		level4Trades = ["vinery:basket|4|1|10|true", "vinery:flower_pot_big|5|1|10|true", "vinery:window|12|1|10|true", "vinery:dark_cherry_beam|6|1|10|true", "vinery:taiga_red_grape_seeds|2|1|5|true", "vinery:taiga_white_grape_seeds|2|1|5|true"]
		level5Trades = ["vinery:wine_box|10|1|10|true", "vinery:lilitu_wine|4|1|10|true", "vinery:calendar|12|1|15|true"]

